---
- name: Install and configure ZFS pool and setup cron job
  hosts: all
  become: true

  tasks:
    - name: Update apt repositories and install zfsutils-linux
      apt:
        update_cache: yes
        name: zfsutils-linux
        state: present

    - name: Verify ZFS version
      command: zfs version
      register: zfs_version_output
      changed_when: false

    - name: Display ZFS version
      debug:
        msg: "ZFS version: {{ zfs_version_output.stdout }}"

    - name: Check if ZFS pool exists
      stat:
        path: /dev/zvol/mypool
      register: zfs_pool_stat

    - name: Create ZFS pool mypool with raidz3 configuration
      shell: >
        zpool create mypool raidz3 /dev/xvdb /dev/xvdc /dev/xvdd /dev/xvde /dev/xvdf
      when: zfs_pool_stat.stat.exists == false
      ignore_errors: yes  # In case the pool already exist

    - name: List ZFS pools to verify creation
      command: zfs list
      register: zfs_list_output
      changed_when: false

    - name: Display ZFS pools
      debug:
        msg: "ZFS pools: {{ zfs_list_output.stdout }}"

    - name: Show ZFS pool status
      command: zpool status
      register: zpool_status_output
      changed_when: false

    - name: Display ZFS pool status
      debug:
        msg: "ZFS pool status: {{ zpool_status_output.stdout }}"

    - name: Check if test file exists in the ZFS pool
      stat:
        path: /mypool/testfile1
      register: test_file_stat
      ignore_errors: yes  # In case the file already exist

    - name: Create a test file in the ZFS pool if not exists
      shell: dd if=/dev/urandom of=/mypool/testfile1 bs=10M count=500
      when: not test_file_stat.stat.exists

    - name: Clone the Ansible-Scripts repository from GitHub
      git:
        repo: https://github.com/babyspy11/Ansible-Scripts.git
        dest: /root/ansible
        clone: yes
        update: yes
        force: yes
    - name: Ensure the /usr/local/bin directory exists
      file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

    - name: Move the zfs-monitor.sh script to /usr/local/bin if it exists
      command: mv /root/ansible/zfs-monitor.sh /usr/local/bin/zfs-monitor.sh
      args:
        #removes: /root/ansible/zfs-monitor.sh
      when: ansible_facts['distribution'] is defined  # Always true, used to prevent playbook parsing error if file is missing

    - name: Set executable permissions on the zfs-monitor.sh script
      file:
        path: /usr/local/bin/zfs-monitor.sh
        mode: '0755'
        state: file

          #- name: Move the cloned playbook file to /root/ansible/zfs_disk_replace.yml if it exists
          #command: mv /root/Ansible-Scripts/zfs_disk_replace.yml /root/ansible/zfs_disk_replace.yml
          #args:
          #removes: /root/ansible/Provisioning.yml
          #ignore_errors: yes  # In case the file doesn't exist or is already moved

    - name: Add cron job to run zfs-monitor.sh every 5 minutes
      cron:
        name: "Run zfs-monitor script every 5 minutes"
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/local/bin/zfs-monitor.sh >> /var/log/zfs-monitor.log 2>&1"
        state: present
